import { EducationCategory } from './educationCategory.model';
import { City } from "./city.model";
import { Work } from "./work.model";

export class Employee{
    id!: number;
    firstName!: string;
    lastName!: string;
    maidenName!: string;
    userName!: string;
    password!: string;
    jmbg!: string;
    idCard!: string;
    sex!: string;
    marriageStatus!: string;
    drivingLicence!: string;
    categoryDl!: string;
    birthDate!: Date;
    birthPlace!: string;
    birthTownship!: string;
    fatherName!: string;
    motherName!: string;
    motherLastName!: string;
    phoneNumber!: string;
    mobilePhone!: string;
    email!: string;
    qualifications!: string;
    profession!: string;
    eduInstitution!: string;
    address!: string;
    place!: string;
    experienceCount!: number;
    citizenship!: string;
    nationality!: string;
    specialKnowledgeAndSkills!: string;
    disability!: string;
    entityOfResidence!: string;
    county!: string;
    municipality!: string;
    bloodType!: string;
    code!: string;
    points!: string;
    cityId!: number;
    city!: City;
    workId!: number;
    work!: Work;
    educationCategoryId!: number;
    educationCategory!: EducationCategory;
    created!: Date;
    modfied!: Date;
    createdBy!: string;
    modifiedBy!: string;
    deleted!: boolean;
    active!: boolean;
  }